project:
  type: website

website:
  title: "My Fastai course Website"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Is_it_a_tennis ?
        href: Is_it_a_tennis_Creating_a_model_from_your_own_data.ipynb